"""Two database backends behind one query interface.

Local runs use **SQLite** - zero configuration, one file, trivially backed up.

Serverless hosts (Vercel among them) give each function instance a read-only
filesystem with only an ephemeral ``/tmp``, so a SQLite file written there is
gone by the next request and is never shared between concurrent instances.
Anywhere the app is deployed that way it must point ``DATABASE_URL`` at a
network **Postgres**; :func:`resolve` picks the backend from that URL.

Both schemas are deliberately *identical in type*, including ISO ``YYYY-MM-DD``
strings for dates rather than a Postgres ``DATE``. The app does all of its date
arithmetic in Python and only ever range-compares dates in SQL, where ISO text
orders correctly - so keeping one row shape means local behaviour and deployed
behaviour cannot quietly diverge.
"""

from __future__ import annotations

import sqlite3
from typing import Any, Iterable, Sequence
from urllib.parse import urlsplit

POSTGRES_SCHEMES = frozenset({"postgres", "postgresql", "psql"})

# Vercel's Postgres integrations export the URL under several names; Neon and
# Supabase use DATABASE_URL, Vercel Postgres adds the POSTGRES_* aliases.
URL_ENV_VARS = ("DATABASE_URL", "POSTGRES_URL", "POSTGRES_PRISMA_URL", "POSTGRES_URL_NON_POOLING")

_SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS receipts (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    name         TEXT    NOT NULL,
    group_key    TEXT    NOT NULL,
    amount_minor INTEGER NOT NULL CHECK (amount_minor > 0),
    date         TEXT    NOT NULL,
    created_at   TEXT    NOT NULL,
    updated_at   TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_receipts_date ON receipts (date);
CREATE INDEX IF NOT EXISTS idx_receipts_group ON receipts (group_key);
"""

_POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS receipts (
    id           BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT    NOT NULL,
    group_key    TEXT    NOT NULL,
    amount_minor BIGINT  NOT NULL CHECK (amount_minor > 0),
    date         TEXT    NOT NULL,
    created_at   TEXT    NOT NULL,
    updated_at   TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_receipts_date ON receipts (date);
CREATE INDEX IF NOT EXISTS idx_receipts_group ON receipts (group_key);
"""


class Database:
    """A connection with a uniform API across sqlite3 and psycopg.

    Queries are written once, in SQLite's ``?`` placeholder style, and
    translated for Postgres. That translation is a plain substitution, which is
    safe only because no query in this app contains a ``?`` inside a literal -
    keep it that way.
    """

    def __init__(self, connection: Any, dialect: str) -> None:
        self._conn = connection
        self.dialect = dialect

    def _sql(self, query: str) -> str:
        return query.replace("?", "%s") if self.dialect == "postgres" else query

    def execute(self, query: str, params: Sequence[Any] = ()) -> Any:
        return self._conn.execute(self._sql(query), tuple(params))

    def executemany(self, query: str, rows: Iterable[Sequence[Any]]) -> None:
        statement = self._sql(query)
        payload = [tuple(r) for r in rows]
        if self.dialect == "postgres":
            with self._conn.cursor() as cur:
                cur.executemany(statement, payload)
        else:
            self._conn.executemany(statement, payload)

    def executescript(self, script: str) -> None:
        if self.dialect == "postgres":
            for statement in filter(None, (s.strip() for s in script.split(";"))):
                self._conn.execute(statement)
            self._conn.commit()
        else:
            self._conn.executescript(script)

    def commit(self) -> None:
        self._conn.commit()

    def close(self) -> None:
        self._conn.close()


def is_postgres_url(url: str | None) -> bool:
    if not url:
        return False
    return urlsplit(url).scheme.split("+")[0].lower() in POSTGRES_SCHEMES


def schema_for(dialect: str) -> str:
    return _POSTGRES_SCHEMA if dialect == "postgres" else _SQLITE_SCHEMA


def connect(config: dict) -> Database:
    """Open a connection to whichever backend this deployment is configured for."""
    url = config.get("DATABASE_URL")
    if is_postgres_url(url):
        return _connect_postgres(url)
    return _connect_sqlite(config["DATABASE"])


def _connect_sqlite(path: str) -> Database:
    conn = sqlite3.connect(path, detect_types=sqlite3.PARSE_DECLTYPES)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    # WAL keeps a long-running read (a chart query) from blocking a write.
    conn.execute("PRAGMA journal_mode = WAL")
    return Database(conn, "sqlite")


def _connect_postgres(url: str) -> Database:
    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError as exc:  # pragma: no cover - depends on the install
        raise RuntimeError(
            "DATABASE_URL points at Postgres but psycopg is not installed. "
            "Add 'psycopg[binary]' to requirements.txt."
        ) from exc

    # autocommit off, matching the sqlite path's explicit commit() calls.
    return Database(
        psycopg.connect(url, row_factory=dict_row, connect_timeout=10),
        "postgres",
    )
