"""Two database backends behind one query interface.

Local runs use **SQLite** - zero configuration, one file, trivially backed up.

Serverless hosts give each function instance a read-only filesystem with only an
ephemeral ``/tmp``, so a SQLite file written there is gone by the next request
and is never shared between concurrent instances. Anywhere the app is deployed
that way it must point ``DATABASE_URL`` at a network **Postgres**;
:func:`connect` picks the backend from that URL.

The two schemas are deliberately identical in type - ISO ``YYYY-MM-DD`` strings
for dates rather than a native ``DATE``, so local behaviour and deployed
behaviour cannot quietly diverge. All date arithmetic happens in Python; SQL
only ever range-compares, where ISO text orders correctly.

Call recordings live in the database as a blob rather than on disk, for the same
reason: on a serverless host there is nowhere durable to put an uploaded file.
:mod:`hrvcoach.recordings` caps the size so a row stays a sane size to move.
"""

from __future__ import annotations

import sqlite3
from typing import Any, Iterable, Sequence
from urllib.parse import urlsplit

POSTGRES_SCHEMES = frozenset({"postgres", "postgresql", "psql"})

# Postgres integrations export the URL under several names; Neon and Supabase
# use DATABASE_URL, Vercel Postgres adds the POSTGRES_* aliases.
URL_ENV_VARS = ("DATABASE_URL", "POSTGRES_URL", "POSTGRES_PRISMA_URL", "POSTGRES_URL_NON_POOLING")

_SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_id   TEXT    NOT NULL UNIQUE,
    full_name     TEXT    NOT NULL,
    role          TEXT    NOT NULL CHECK (role IN ('admin', 'employee')),
    team          TEXT    NOT NULL DEFAULT '',
    password_hash TEXT    NOT NULL,
    active        INTEGER NOT NULL DEFAULT 1,
    created_at    TEXT    NOT NULL
);
CREATE TABLE IF NOT EXISTS coaching_logs (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_uid    INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    coach_uid       INTEGER REFERENCES users (id) ON DELETE SET NULL,
    session_date    TEXT    NOT NULL,
    week_start      TEXT    NOT NULL,
    category        TEXT    NOT NULL,
    metric_key      TEXT    NOT NULL DEFAULT '',
    opportunity     TEXT    NOT NULL,
    root_cause      TEXT    NOT NULL DEFAULT '',
    action_plan     TEXT    NOT NULL,
    support         TEXT    NOT NULL DEFAULT '',
    follow_up_date  TEXT    NOT NULL DEFAULT '',
    status          TEXT    NOT NULL DEFAULT 'open',
    acknowledged_at TEXT    NOT NULL DEFAULT '',
    created_at      TEXT    NOT NULL,
    updated_at      TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_logs_employee ON coaching_logs (employee_uid, session_date);
CREATE INDEX IF NOT EXISTS idx_logs_week ON coaching_logs (week_start);
CREATE TABLE IF NOT EXISTS recordings (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    log_id       INTEGER NOT NULL REFERENCES coaching_logs (id) ON DELETE CASCADE,
    filename     TEXT    NOT NULL,
    content_type TEXT    NOT NULL,
    size_bytes   INTEGER NOT NULL CHECK (size_bytes > 0),
    call_ref     TEXT    NOT NULL DEFAULT '',
    data         BLOB    NOT NULL,
    uploaded_at  TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_recordings_log ON recordings (log_id);
CREATE TABLE IF NOT EXISTS metrics (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_uid INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    week_start  TEXT    NOT NULL,
    metric_key  TEXT    NOT NULL,
    value       REAL    NOT NULL,
    note        TEXT    NOT NULL DEFAULT '',
    created_at  TEXT    NOT NULL,
    updated_at  TEXT    NOT NULL,
    UNIQUE (employee_uid, week_start, metric_key)
);
CREATE INDEX IF NOT EXISTS idx_metrics_week ON metrics (week_start);
"""

_POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   TEXT    NOT NULL UNIQUE,
    full_name     TEXT    NOT NULL,
    role          TEXT    NOT NULL CHECK (role IN ('admin', 'employee')),
    team          TEXT    NOT NULL DEFAULT '',
    password_hash TEXT    NOT NULL,
    active        INTEGER NOT NULL DEFAULT 1,
    created_at    TEXT    NOT NULL
);
CREATE TABLE IF NOT EXISTS coaching_logs (
    id              BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_uid    BIGINT  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    coach_uid       BIGINT  REFERENCES users (id) ON DELETE SET NULL,
    session_date    TEXT    NOT NULL,
    week_start      TEXT    NOT NULL,
    category        TEXT    NOT NULL,
    metric_key      TEXT    NOT NULL DEFAULT '',
    opportunity     TEXT    NOT NULL,
    root_cause      TEXT    NOT NULL DEFAULT '',
    action_plan     TEXT    NOT NULL,
    support         TEXT    NOT NULL DEFAULT '',
    follow_up_date  TEXT    NOT NULL DEFAULT '',
    status          TEXT    NOT NULL DEFAULT 'open',
    acknowledged_at TEXT    NOT NULL DEFAULT '',
    created_at      TEXT    NOT NULL,
    updated_at      TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_logs_employee ON coaching_logs (employee_uid, session_date);
CREATE INDEX IF NOT EXISTS idx_logs_week ON coaching_logs (week_start);
CREATE TABLE IF NOT EXISTS recordings (
    id           BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id       BIGINT  NOT NULL REFERENCES coaching_logs (id) ON DELETE CASCADE,
    filename     TEXT    NOT NULL,
    content_type TEXT    NOT NULL,
    size_bytes   BIGINT  NOT NULL CHECK (size_bytes > 0),
    call_ref     TEXT    NOT NULL DEFAULT '',
    data         BYTEA   NOT NULL,
    uploaded_at  TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_recordings_log ON recordings (log_id);
CREATE TABLE IF NOT EXISTS metrics (
    id           BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_uid BIGINT  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    week_start   TEXT    NOT NULL,
    metric_key   TEXT    NOT NULL,
    value        DOUBLE PRECISION NOT NULL,
    note         TEXT    NOT NULL DEFAULT '',
    created_at   TEXT    NOT NULL,
    updated_at   TEXT    NOT NULL,
    UNIQUE (employee_uid, week_start, metric_key)
);
CREATE INDEX IF NOT EXISTS idx_metrics_week ON metrics (week_start);
"""


class Database:
    """A connection with a uniform API across sqlite3 and psycopg.

    Queries are written once, in SQLite's ``?`` placeholder style, and
    translated for Postgres. That translation is a plain substitution, which is
    safe only because no query in this app contains a ``?`` inside a literal -
    keep it that way.
    """

    def __init__(self, connection: Any, dialect: str) -> None:
        self._conn = connection
        self.dialect = dialect

    def _sql(self, query: str) -> str:
        return query.replace("?", "%s") if self.dialect == "postgres" else query

    def execute(self, query: str, params: Sequence[Any] = ()) -> Any:
        return self._conn.execute(self._sql(query), tuple(params))

    def executemany(self, query: str, rows: Iterable[Sequence[Any]]) -> None:
        statement = self._sql(query)
        payload = [tuple(r) for r in rows]
        if self.dialect == "postgres":
            with self._conn.cursor() as cur:
                cur.executemany(statement, payload)
        else:
            self._conn.executemany(statement, payload)

    def executescript(self, script: str) -> None:
        if self.dialect == "postgres":
            for statement in filter(None, (s.strip() for s in script.split(";"))):
                self._conn.execute(statement)
            self._conn.commit()
        else:
            self._conn.executescript(script)

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()

    def close(self) -> None:
        self._conn.close()


def is_postgres_url(url: str | None) -> bool:
    if not url:
        return False
    return urlsplit(url).scheme.split("+")[0].lower() in POSTGRES_SCHEMES


def schema_for(dialect: str) -> str:
    return _POSTGRES_SCHEMA if dialect == "postgres" else _SQLITE_SCHEMA


def blob(data: bytes, dialect: str) -> Any:
    """Wrap raw bytes so each driver stores them as a binary column."""
    return sqlite3.Binary(data) if dialect == "sqlite" else data


def connect(config: dict) -> Database:
    """Open a connection to whichever backend this deployment is configured for."""
    url = config.get("DATABASE_URL")
    if is_postgres_url(url):
        return _connect_postgres(url)
    return _connect_sqlite(config["DATABASE"])


def _connect_sqlite(path: str) -> Database:
    conn = sqlite3.connect(path, detect_types=sqlite3.PARSE_DECLTYPES)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    # WAL keeps a long-running read (a chart query) from blocking a write.
    conn.execute("PRAGMA journal_mode = WAL")
    return Database(conn, "sqlite")


def _connect_postgres(url: str) -> Database:
    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError as exc:  # pragma: no cover - depends on the install
        raise RuntimeError(
            "DATABASE_URL points at Postgres but psycopg is not installed. "
            "Add 'psycopg[binary]' to requirements.txt."
        ) from exc

    # autocommit off, matching the sqlite path's explicit commit() calls.
    return Database(
        psycopg.connect(url, row_factory=dict_row, connect_timeout=10),
        "postgres",
    )
