import Link from "next/link";
import { notFound } from "next/navigation";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { Forbidden } from "@/components/admin/Forbidden";
import { formatCentavosAsPHP } from "@/lib/money";
import { STORE_NAME } from "@/lib/store-config";
import { PrintButton } from "@/components/admin/PrintButton";

export const dynamic = "force-dynamic";

type Adjustment = { label: string; amountCentavos: number };

export default async function PayslipPage({ params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions);
  if (!session?.user || session.user.role !== "OWNER") {
    return <Forbidden />;
  }

  const payslip = await prisma.payslip.findUnique({ where: { id: params.id } });
  if (!payslip) notFound();

  const adjustments = Array.isArray(payslip.adjustments) ? (payslip.adjustments as unknown as Adjustment[]) : [];
  const adjustmentsTotalCentavos = adjustments.reduce((sum, a) => sum + a.amountCentavos, 0);

  const dateFormatter = new Intl.DateTimeFormat("en-PH", { timeZone: "Asia/Manila", dateStyle: "medium" });

  return (
    <div className="mx-auto max-w-md">
      <Link href="/admin/payroll" className="text-sm text-neutral-500 hover:text-neutral-800 print:hidden">
        &larr; Back to Payroll
      </Link>

      <div className="mt-4 rounded-2xl border border-neutral-200 bg-white p-6 font-mono text-sm print:border-none print:p-0">
        <div className="text-center">
          <p className="text-base font-semibold">{STORE_NAME}</p>
          <p className="mt-2 text-xs text-neutral-500">Payslip</p>
          <p className="text-xs text-neutral-500">
            {dateFormatter.format(payslip.periodStart)} – {dateFormatter.format(payslip.periodEnd)}
          </p>
        </div>

        <div className="mt-4 border-t border-dashed border-neutral-300 pt-4">
          <div className="flex justify-between py-0.5">
            <span>Employee</span>
            <span>{payslip.employeeName}</span>
          </div>
          {payslip.position && (
            <div className="flex justify-between py-0.5">
              <span>Position</span>
              <span>{payslip.position}</span>
            </div>
          )}
        </div>

        <div className="mt-3 flex flex-col gap-0.5 border-t border-dashed border-neutral-300 pt-3">
          <div className="flex justify-between">
            <span>Base pay</span>
            <span>{formatCentavosAsPHP(payslip.basePayCentavos)}</span>
          </div>
          {adjustments.map((a, i) => (
            <div key={i} className="flex justify-between">
              <span>{a.label}</span>
              <span>
                {a.amountCentavos < 0 ? "-" : ""}
                {formatCentavosAsPHP(Math.abs(a.amountCentavos))}
              </span>
            </div>
          ))}
          {adjustments.length > 0 && (
            <div className="flex justify-between text-neutral-500">
              <span>Adjustments total</span>
              <span>
                {adjustmentsTotalCentavos < 0 ? "-" : ""}
                {formatCentavosAsPHP(Math.abs(adjustmentsTotalCentavos))}
              </span>
            </div>
          )}
          <div className="flex justify-between text-base font-semibold">
            <span>NET PAY</span>
            <span>{formatCentavosAsPHP(payslip.netPayCentavos)}</span>
          </div>
        </div>

        {payslip.generatedByName && (
          <p className="mt-6 text-center text-xs text-neutral-400">Generated by {payslip.generatedByName}</p>
        )}
      </div>

      <div className="mt-5">
        <PrintButton label="Print payslip" />
      </div>
    </div>
  );
}
